language: go

go:
- 1.5
addons:
  postgresql: "9.4"
services:
  - redis-server
  - postgresql
before_script: 
	- go get github.com/omarqazi/hearst/...
	- go get bitbucket.org/liamstask/goose/cmd/goose
	- goose -env testing up
script: go test -v ./...
env:
- HEARST_POSTGRES=dbname=travis_ci_test user=postgres sslmode=disable