addons:
  postgresql: "9.4"
before_script: 
  - go get github.com/omarqazi/hearst/...
  - go get bitbucket.org/liamstask/goose/cmd/goose
  - goose -env testing up
env:
  - HEARST_POSTGRES=dbname=travis_ci_test user=postgres sslmode=disable
language: go
go:
- 1.5
script: make test
services:
  - redis-server
  - postgresql
