addons:
  postgresql: "9.6"
before_script:
  - go get .
  - go get bitbucket.org/liamstask/goose/cmd/goose
  - sudo apt-get update
  - sudo apt-get install -y postgresql-9.6-postgis-2.3
  - psql -c 'create database hearst;' -U postgres
  - goose -env testing up
env:
  - HEARST_POSTGRES="dbname=hearst user=postgres sslmode=disable"
language: go
go:
- 1.11
script: make test
services:
  - redis-server
  - postgresql
notifications:
  slack: spreemobile:c2CbzAyiMkDCJh4QcpovcfPW