addons:
  postgresql: "9.4"
before_script:
  - go get .
  - go get bitbucket.org/liamstask/goose/cmd/goose
  - psql -c 'create database hearst;' -U postgres
  - goose -env testing up
env:
  - HEARST_POSTGRES="dbname=hearst user=postgres sslmode=disable"
language: go
go:
- 1.5
script: make test
services:
  - redis-server
  - postgresql
notifications:
  slack: spreemobile:c2CbzAyiMkDCJh4QcpovcfPW